name: dev-cli
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Unit tests
        run: make test

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
